### ISSUE TITLE
Some problems encountered by novices in reproducing engineering code

### ISSUE THREAD

**Issue by jinglin-byte** [Xylon-Sean/rfnet#20]
Error result display：
D:/金林/pytorch/rfnet-master/rfnet/train.py:310: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with autograd.detect_anomaly():
D:\pytools\Anaconda3\envs\rfnet\lib\site-packages\torch\nn\functional.py:3826: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
D:\金林\pytorch\rfnet-master\rfnet\model\rf_det_module.py:202: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  None, None, :, :
Traceback (most recent call last):
  File "D:/金林/pytorch/rfnet-master/rfnet/train.py", line 422, in <module>
    train()
  File "D:/金林/pytorch/rfnet-master/rfnet/train.py", line 314, in train
    endpoint = model(batch)
  File "D:\pytools\Anaconda3\envs\rfnet\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\金林\pytorch\rfnet-master\rfnet\model\rf_net_so.py", line 48, in forward
    im2_rawsc, homo12
  File "D:\金林\pytorch\rfnet-master\rfnet\model\rf_net_module.py", line 39, in gtscore
    im1gt_score, topk_mask, topk_value = self.det.process(im1w_score)
  File "D:\金林\pytorch\rfnet-master\rfnet\model\rf_det_module.py", line 209, in process
    padding=self.GAUSSIAN_KSIZE // 2,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

Process finished with exit code 1

RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same。

**Comment by luanyue-ly** [comment]
I also encountered this problem. How did you solve it ？

**Comment by 1369841815** [comment]
Has this problem been solved？
