### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by luanyue-ly** [Xylon-Sean/rfnet#21]
11-11 02:03:53 : Prepare for repetition
True
11-11 02:03:53 : Build the model
cuda:0
True
11-11 02:03:56 : Loading traning data
11-11 02:03:56 : /mnt/rfnet/data/hpatch_v_sequence has 235 pair images
11-11 02:04:00 : Loading evaluation data
11-11 02:04:00 : /mnt/rfnet/data/hpatch_v_sequence has 30 pair images
11-11 02:04:01 : Loading testing data
11-11 02:04:01 : /mnt/rfnet/data/hpatch_v_sequence has 30 pair images
11-11 02:04:02 : Start training
train.py:318: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with autograd.detect_anomaly():
/opt/conda/envs/rfnet/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/mnt/rfnet/model/rf_net_module.py:53: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  half_scale = im2_scale // 2
/opt/conda/envs/rfnet/lib/python3.7/site-packages/torch/nn/functional.py:4004: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
/mnt/rfnet/model/rf_det_module.py:202: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  None, None, :, :
Traceback (most recent call last):
  File "train.py", line 430, in <module>
    train()
  File "train.py", line 322, in train
    endpoint = model(batch).cuda()
  File "/opt/conda/envs/rfnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/rfnet/model/rf_net_so.py", line 48, in forward
    im2_rawsc, homo12
  File "/mnt/rfnet/model/rf_net_module.py", line 39, in gtscore
    im1gt_score, topk_mask, topk_value = self.det.process(im1w_score).cuda()
  File "/mnt/rfnet/model/rf_det_module.py", line 209, in process
    padding=self.GAUSSIAN_KSIZE // 2,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by grexai** [comment]
i have  also met with this issue,
On torch forums, they say you need to push the model and/or data to the device. The model is 100% pushed. But i couldnt push the data to device

**Comment by pvtoan** [comment]
Hi, 
I run example.py file but I got the same problem.

In fact, I already have the command "device = torch.device('cuda'); model = model.to(device)" but it is still said that 
"RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same"

Anyone fixed this problem, please let me know.

Thank you!
